# Generated by Django 5.0.7 on 2024-07-27 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_brand_cars'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cars',
            name='descripition',
        ),
        migrations.RemoveField(
            model_name='cars',
            name='stock',
        ),
        migrations.AddField(
            model_name='cars',
            name='observation',
            field=models.TextField(null=True, verbose_name='Observação'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='brand_name',
            field=models.CharField(max_length=225, unique=True, verbose_name='Marca do Veículo'),
        ),
    ]
