# Generated by Django 5.0.7 on 2024-07-27 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_cars_descripition_remove_cars_stock_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cars',
            name='image',
        ),
        migrations.AddField(
            model_name='cars',
            name='car_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/cars'),
        ),
    ]
